.gitignore
aws/values-amazon-primary.yaml
aws/values-amazon-secondary.yaml
azure/values-azure-primary.yaml
azure/values-azure-secondary.yaml
gcp/README.md
gcp/values-google-primary.yaml
gcp/values-google-secondary.yaml
private-registry-helm-values/values-private-container-registry.yaml

Fixing a few issues, please review carefully. 
Added this:
https://guide.kubecost.com/hc/en-us/articles/6446286863383-Tuning-Resource-Consumption#on-secondaries-disabling-cloud-assets-and-running-kubecost-in-agent-mode-with-etl-and-caching-disabled

Clean configs

---

.gitignore
aws-attach-roles/README.md
aws-attach-roles/cloud-integration.json
aws-attach-roles/object-store.yaml
aws-attach-roles/values-amazon-primary.yaml

Please check for glaring errors.
Goal is to remove all service account keys from config files.

aws-attach-iam-roles

---

aws/values-amazon-primary.yaml
azure/values-azure-primary.yaml
gcp/values-google-primary.yaml

Adding the value to turn on collection to each of the three cloud, commenting out the ones not used for each cloud

adding the network cloud services value

---

helm-limits/requests-and-limits.yaml

Thanks to Sean for most of this.

requests and limits for all

---

argocd/README.md
argocd/argocd-kubecost-free.yaml

making cloud-integration optional for now in the enterprise setup.

argo update

---

custom-tsdb/README.md
custom-tsdb/values-primary.yaml
custom-tsdb/values-secondary.yaml

Additional detail for using the serviceMonitor

serviceMonitor detail

---

azure/README-enterprise.md
azure/cloud-integration.json

adding the gov option for azure users who are using Azure gov

adding azure gov cloud for cloud-integration

---

saml-azuread/README.md
saml-azuread/filters-examples.json
saml-okta/README.md
saml-okta/filters-examples.json

This feature was added in v1.99:
*  https://github.com/kubecost/cost-analyzer-helm-chart/issues/1799

Add examples for RBAC filtering by Labels and Annotations

---

custom-tsdb/values-primary.yaml
custom-tsdb/values-secondary.yaml

This is what we spoke about yesterday- look right?

add prom cluster_id

---

etl-federation/README.md
etl-federation/agent-federated.yaml
etl-federation/federated-store.yaml
etl-federation/object-store.yaml
etl-federation/policy-kubecost-aws-s3.json
etl-federation/primary-federator.yaml

Etl federation

---

custom-tsdb/values-primary.yaml
custom-tsdb/values-secondary.yaml

missed a comment in previous PR

serviceMonitor update

---

scripts/README.md
scripts/python/kubecost-api/README.md
scripts/python/kubecost-api/assets-api-aws-s3.py
scripts/python/kubecost-api/etl-api.py
scripts/python/kubecost-api/json-to-jsonl-example.py

This is the start of the 'scripts' directory intended to have scripts in different languages used to interact with various parts of kubecost.  The first set of scripts are written in python for interacting with the kubecost REST API.  The first examples are a bit specific, but additional more general scripts will be created.  These scripts are good examples for customers who need to pull data using the API as part of a job, cronjob, cloud function, manually, etc.

Python Scripts

---

argocd/kubecost-cluster-settings.yaml
aws-attach-roles/values-amazon-primary.yaml
aws/values-amazon-primary.yaml
azure/values-azure-primary.yaml
custom-tsdb/values-primary.yaml
etl-federation/existing-prometheus/primary-federator.yaml
etl-federation/primary-federator.yaml
gcp/values-google-primary.yaml

Update to use cloudCost by default

Update to use cloudCost by default

---

etl-federation/README.md
etl-federation/federated-store.yaml
etl-federation/policy-kubecost-aws-s3.json
etl-federation/primary-federator.yaml

@linhlam-kc, if you get a moment, would you mind reviewing the IAM policy? Not urgent. Feel free to merge when done.
The other changes are just clarifications.

federated policy and readme

---

etl-federation/README.md
etl-federation/existing-prometheus/README.md
etl-federation/existing-prometheus/agent-federated.yaml
etl-federation/existing-prometheus/policy-kubecost-aws-s3.json
etl-federation/existing-prometheus/primary-federator.yaml

Clean up readme
disable grafana on federated ETL
KSM dedupe
added to primary configs:
```
federatedETL:
federator:
primaryClusterID: CLUSTER_NAME
```

etl-federation updates

---

aws-attach-roles/README-AWS-ROSA.md
etl-federation/README.md
etl-federation/README_AWS_ROSA

Add instructions to set up multi AWS ROSA clusters with etl-federation (IRSA)

Add instructions to set up multi AWS ROSA clusters with etl-federation

---

etl-federation/existing-prometheus/agent-federated.yaml
etl-federation/existing-prometheus/primary-federator.yaml

remove reference to thanos and add Prometheus crd opttions

Etl fed update

---

ingress-examples/README.md
oidc-azuread/README.md
saml-okta/README.md

Some docs on SAML encryption also sneaking in here too

Docs for OIDC/RBAC on AzureAD

---

aws-attach-roles/README.md

irsa update

---

datadog/README.MD

Updates Datadog article with link to our updated version

Updates Datadog doc with disclaimer

---

argocd/federated-etl-argo/argocd-kubecost-primary.yaml
argocd/federated-etl-argo/argocd-kubecost-secondary.yaml

Small changes to values files paths in argo configs.

Argo Values Changles

---

kubebox/Dockerfile
kubebox/README.md
kubebox/kubebox.yaml
scripts/aws/audit/kubecost-aws-audit-instance_id.py
scripts/aws/audit/kubecost-aws-audit-services.py
scripts/aws/audit/kubecost-aws-audit-tag.py

Adding new Kubebox docker image configuration and aws audit scripts

Adding kubebox image and aws audit scripts

---

fluxcd/README.md
fluxcd/federated-etl-flux/README.md
fluxcd/federated-etl-flux/cloud-integration.json
fluxcd/federated-etl-flux/federated-store.yaml
fluxcd/federated-etl-flux/helmrelease-flux-primary.yaml
fluxcd/federated-etl-flux/helmrelease-flux-secondary.yaml
fluxcd/federated-etl-flux/helmrepo.yaml
fluxcd/federated-etl-flux/iam-kubecost-metrics-s3-policy.json
fluxcd/federated-etl-flux/kustomization.yaml

**Title:**  FluxCD Support with Enhanced KubecostAggregator Configurations
**Description:**
This pull request introduces comprehensive support for FluxCD across our project repositories, including a significant enhancement to the `kubecostAggregator` setup. This update bridges a crucial gap in our infrastructure automation, specifically targeting the absence of FluxCD support in our open repositories and the `poc-common-configurations`.
**Key Contributions:**
- **FluxCD Integration**: Implemented thorough documentation and YAML configurations to seamlessly integrate FluxCD. This allows for an automated, GitOps-driven approach to manage cluster configurations and deployments.
- **KubecostAggregator Enhancement**: Updated the `kubecostAggregator` configuration to the latest version, …

Added FluxCD Configs to poc-common-configurations

---

aws/iam-policies/amp/iam-read-amp-metrics.json

Update AWS IAM policy to include region and account ID #107

---

aws/etl-federation/values-amazon-primary.yaml
aws/etl-federation/values-amazon-secondary.yaml
azure/README-enterprise.md
azure/values-azure-primary.yaml
azure/values-azure-secondary.yaml
etl-federation-aggregator/README.md
etl-federation-aggregator/primary-aggregator.yaml
etl-federation-aggregator/secondary-federated.yaml
gcp/README-enterprise.md
gcp/README-gcp-storage.md
gcp/values-google-primary.yaml
gcp/values-google-secondary.yaml

Clearing out defaults from values files

Clearing out defaults from values files

---

etl-federation-aggregator/README.md
etl-federation-aggregator/coud-integration.json

Signed-off-by: jesse goodier <31039225+jessegoodier@users.noreply.github.com>

Example multi-provider cloud-integration
